table FactSalesTarget
	lineageTag: efa0be22-2c48-4dfa-b9e0-b24f1c23fe06

	measure 'Ice Cream Total Target' = 620000
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b8312a21-b4e6-4cbe-8122-f0c356d57986

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Month Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9351aa7b-0ede-49f7-887a-6232a544ed74
		summarizeBy: none
		sourceColumn: Month Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YearMonth
		dataType: string
		lineageTag: 1b7916f9-4988-4e64-8575-1365d1b078de
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 3deb158b-7a29-4c16-aeee-97576b8ebbfd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 8aab0591-d5e1-4203-8388-474cdf81f28d
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Salesperson
		dataType: string
		lineageTag: 74310436-f7f4-4d19-ac45-ec68ae10f330
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column 'KPI Target'
		dataType: double
		lineageTag: da7cec04-3ee6-4099-965c-e4589c0094ca
		summarizeBy: sum
		sourceColumn: KPI Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Company
		dataType: string
		lineageTag: 3e2175b1-7430-41c0-8dd4-cb8a6b01fec2
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition FactSalesTarget = m
		mode: import
		source =
				let
				    Source = Excel.Workbook((if Text.StartsWith(DataRoot, "http") then Web.Contents(DataRoot & "/sales_targets_monthly.xlsx") else File.Contents(DataRoot & "\sales_targets_monthly.xlsx")), null, true),
				    #"SALES 0824_Sheet" = Source{[Item="KPI by Month",Kind="Sheet"]}[Data],
				    #"Promoted Headers1" = Table.PromoteHeaders(#"SALES 0824_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Month Date", type date}, {"KPI Target", type number}, {"Company", type text}, {"Salesperson", type text}, {"YearMonth", type text}, {"Year", type text}, {"Month", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

