table FactInventoryLot
	lineageTag: ed3bf3c8-065d-4a32-aa21-e863113dc28f

	measure 'Estimated Loss Value' = SUM(FactInventoryLot[On Hand Qty])*SUM(FactInventoryLot[Product/Base Cost])
		lineageTag: d135fb6f-980a-4b6d-9e44-831a103e60da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days to Expiry' =
			
			VAR ExpiryDate =
			    CALCULATE(
			        MIN(FactInventoryLot[Expiry Date])
			        )
			RETURN
			    IF(
			        NOT HASONEVALUE(FactInventoryLot[Lot/Serial Number])
			            || ISBLANK(ExpiryDate),
			        BLANK(),
			        DATEDIFF(
			            TODAY(),
			            ExpiryDate,
			            DAY
			        )
			    )
		formatString: 0
		lineageTag: f51ff150-005d-4812-9495-25f905eb969b

	column 'Lot/Serial Number'
		dataType: string
		lineageTag: 5a23dad4-3c69-4b38-b537-567b5d8a2971
		summarizeBy: none
		sourceColumn: Lot/Serial Number

		annotation SummarizationSetBy = Automatic

	column 'Internal Reference'
		dataType: string
		lineageTag: 9773644d-60d7-488c-9717-856c7bc5c195
		summarizeBy: none
		sourceColumn: Internal Reference

		annotation SummarizationSetBy = Automatic

	column 'Product/Internal Reference'
		dataType: string
		lineageTag: 68fb1a59-8e49-44cc-ae63-6a7909a4be4f
		summarizeBy: none
		sourceColumn: Product/Internal Reference

		annotation SummarizationSetBy = Automatic

	column Product/Name
		dataType: string
		lineageTag: 619747f3-a12d-4dc0-aa98-9c20f42afede
		summarizeBy: none
		sourceColumn: Product/Name

		annotation SummarizationSetBy = Automatic

	column 'Product/Product Category/Parent Name'
		dataType: string
		lineageTag: 05cd1c3f-7e68-4206-9edd-1b7eba52d877
		summarizeBy: none
		sourceColumn: Product/Product Category/Parent Name

		annotation SummarizationSetBy = Automatic

	column 'Product/Product Category/Category Name'
		dataType: string
		lineageTag: e8b84cb8-1a67-470e-95ff-b775eeaa37c9
		summarizeBy: none
		sourceColumn: Product/Product Category/Category Name

		annotation SummarizationSetBy = Automatic

	column 'Product/CN Brand'
		dataType: string
		lineageTag: ac3c73bc-6133-4598-8836-f038039ca214
		summarizeBy: none
		sourceColumn: Product/CN Brand

		annotation SummarizationSetBy = Automatic

	column 'Display Name'
		dataType: string
		lineageTag: 0e57f34b-836a-41a3-b870-69c1271e60ec
		summarizeBy: none
		sourceColumn: Display Name

		annotation SummarizationSetBy = Automatic

	column 'On Hand Qty'
		dataType: int64
		formatString: 0
		lineageTag: d030762e-282d-495f-a2c8-2b83c2bb3e79
		summarizeBy: sum
		sourceColumn: On Hand Qty

		annotation SummarizationSetBy = Automatic

	column 'Expiry Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8c4c9ebb-9071-402f-a215-c0e2be06f2c1
		summarizeBy: none
		sourceColumn: Expiry Date

		variation Variation
			isDefault
			relationship: 77f8dfae-ac84-4c3f-8996-d357afd9942a
			defaultHierarchy: LocalDateTable_cbdd9f09-e630-4f65-b4e5-17481f8142bc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Product/Lot Available'
		dataType: double
		lineageTag: 30c8e65e-bce2-495c-8746-573bdae78ce5
		summarizeBy: sum
		sourceColumn: Product/Lot Available

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product/Forecast Qty'
		dataType: double
		lineageTag: aa2d2466-7fbf-4155-aa37-10404e43a34c
		summarizeBy: sum
		sourceColumn: Product/Forecast Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product/Pallet
		dataType: string
		lineageTag: d2e6df71-f705-46ee-a352-fc64c25e63c7
		summarizeBy: none
		sourceColumn: Product/Pallet

		annotation SummarizationSetBy = Automatic

	column 'Product/Unit of Measure'
		dataType: string
		lineageTag: bd65d10a-4f06-4592-bc9a-adab67d1f025
		summarizeBy: none
		sourceColumn: Product/Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'Product/Base Cost'
		dataType: double
		lineageTag: b6096da7-1d2c-4f6c-86e3-0479c497f3af
		summarizeBy: sum
		sourceColumn: Product/Base Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Activity
		dataType: string
		lineageTag: 59b24922-d7d6-4259-a677-2e0860831359
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Product/Expiry Date'
		dataType: int64
		formatString: 0
		lineageTag: 1ee53e2c-5700-4bbc-b683-781ac6368734
		summarizeBy: sum
		sourceColumn: Product/Expiry Date

		annotation SummarizationSetBy = Automatic

	column 'Product/Sales Price'
		dataType: double
		lineageTag: 6ab72660-4ea9-40b6-9a2f-c3378f81fd29
		summarizeBy: sum
		sourceColumn: Product/Sales Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Expiry Status' =
			
			VAR DaysLeft =
			    FactInventoryLot[Days to Expiry]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(DaysLeft), "No Expiry Date",
			        DaysLeft <= 0, "Expired",
			        DaysLeft <= 30, "Expires Within 30 Days",
			        DaysLeft <= 90, "31-90 Days to Expiry",
			        DaysLeft <= 180, "91-180 Days to Expiry",
			        "Normal"
			    )
		lineageTag: f1043dc4-c1af-4aa2-b1f9-dc8e134a28aa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Shelf Life Progress' =
			
			VAR ShelfLifeDays =
			    FactInventoryLot[Product/Expiry Date]
			VAR RemainingDays =
			    DATEDIFF(
			        TODAY(),
			        FactInventoryLot[Expiry Date],
			        DAY
			    )
			RETURN
			    IF(
			        ISBLANK(FactInventoryLot[Expiry Date])
			            || ISBLANK(ShelfLifeDays)
			            || ShelfLifeDays <= 0,
			        BLANK(),
			        MAX(
			            0,
			            MIN(
			                1,
			                DIVIDE(
			                    ShelfLifeDays - RemainingDays,
			                    ShelfLifeDays
			                )
			            )
			        )
			    )
		lineageTag: b1362daf-5ad9-4860-9f1f-726665b7de49
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Company
		dataType: string
		lineageTag: e0bd6938-eec9-4c97-aefb-337491ec0a0e
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition FactInventoryLot = m
		mode: import
		source =
				let
				    Source = Csv.Document((if Text.StartsWith(DataRoot, "http") then Web.Contents(DataRoot & "/inventory_lots.csv") else File.Contents(DataRoot & "\inventory_lots.csv")),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Lot/Serial Number", type text}, {"Internal Reference", type text}, {"Product/Internal Reference", type text}, {"Product/Name", type text}, {"Product/Product Category/Parent Name", type text}, {"Product/Product Category/Category Name", type text}, {"Product/CN Brand", type text}, {"Display Name", type text}, {"On Hand Qty", Int64.Type}, {"Expiry Date", type date}, {"Product/Lot Available", type number}, {"Product/Forecast Qty", type number}, {"Product/Pallet", type text}, {"Product/Unit of Measure", type text}, {"Product/Base Cost", type number}, {"Activity", type text}, {"Product/Expiry Date", Int64.Type}, {"Product/Sales Price", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

