table FactSalesAll
	lineageTag: d09fedcd-1dea-46b6-a82a-513ed602ec48

	column 发票编号
		dataType: string
		lineageTag: 071a860c-db4b-413b-9f45-cf0f45dd6ca3
		summarizeBy: none
		sourceColumn: 发票编号

		annotation SummarizationSetBy = Automatic

	column 产品/内部参考号
		dataType: string
		lineageTag: 304240f6-63c4-439f-b0a2-c9740a9a1112
		summarizeBy: none
		sourceColumn: 产品/内部参考号

		annotation SummarizationSetBy = Automatic

	column 产品/名称
		dataType: string
		lineageTag: 315d6afd-402e-4f57-bdba-5234faaaef9e
		summarizeBy: none
		sourceColumn: 产品/名称

		annotation SummarizationSetBy = Automatic

	column '产品/CN 品牌'
		dataType: string
		lineageTag: 2e6ec8c4-13ce-4041-bf73-5a9f09a437f9
		summarizeBy: none
		sourceColumn: 产品/CN 品牌

		annotation SummarizationSetBy = Automatic

	column 产品/产品类别/中文名称
		dataType: string
		lineageTag: 7145420d-c116-4885-876d-da730d056b4f
		summarizeBy: none
		sourceColumn: 产品/产品类别/中文名称

		annotation SummarizationSetBy = Automatic

	column 产品/产品类别/上级名称
		dataType: string
		lineageTag: 2c9fbb8b-6fee-456c-a40a-6fea33083ec9
		summarizeBy: none
		sourceColumn: 产品/产品类别/上级名称

		annotation SummarizationSetBy = Automatic

	column 产品/计量单位
		dataType: string
		lineageTag: 20c7504e-b879-4611-a796-4e918b75c908
		summarizeBy: none
		sourceColumn: 产品/计量单位

		annotation SummarizationSetBy = Automatic

	column 合作伙伴
		dataType: string
		lineageTag: 7dc1b2bf-ca0d-4781-a548-ee33bb0ad567
		summarizeBy: none
		sourceColumn: 合作伙伴

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/参考
		dataType: string
		lineageTag: be1cd5ca-cff1-421a-b8bf-0c9730689a10
		summarizeBy: none
		sourceColumn: 合作伙伴/参考

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/销售员
		dataType: string
		lineageTag: 8d77ae84-3762-46ff-9332-14b9910da845
		summarizeBy: none
		sourceColumn: 合作伙伴/销售员

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/客户类型
		dataType: string
		lineageTag: ca1b338f-0931-4fc7-8182-7f7713e538c2
		summarizeBy: none
		sourceColumn: 合作伙伴/客户类型

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/完整地址
		dataType: string
		lineageTag: 28090ffc-bead-4254-a322-802d99e0abd3
		summarizeBy: none
		sourceColumn: 合作伙伴/完整地址

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/城市
		dataType: string
		lineageTag: d973d85e-74b3-4d04-8fa5-3ab100d5c323
		summarizeBy: none
		sourceColumn: 合作伙伴/城市

		annotation SummarizationSetBy = Automatic

	column 合作伙伴/省/州
		dataType: string
		lineageTag: 046f8bce-4d9b-4e58-8739-ca95067ab83a
		summarizeBy: none
		sourceColumn: 合作伙伴/省/州

		annotation SummarizationSetBy = Automatic

	column 销售订单行/销售人员
		dataType: string
		lineageTag: 0bfd4aad-ef12-4b3a-a0b4-6b6b80431552
		summarizeBy: none
		sourceColumn: 销售订单行/销售人员

		annotation SummarizationSetBy = Automatic

	column 销售订单行/创建人
		dataType: string
		lineageTag: a2f74487-18cf-417d-912a-06107ea99e6a
		summarizeBy: none
		sourceColumn: 销售订单行/创建人

		annotation SummarizationSetBy = Automatic

	column 单价
		dataType: double
		lineageTag: 81409efa-3e6a-4d73-9636-a3c555b7a317
		summarizeBy: sum
		sourceColumn: 单价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 小计
		dataType: double
		lineageTag: 835c524a-9964-4b20-99f7-d2f1957d442f
		summarizeBy: sum
		sourceColumn: 小计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 产品/基准成本
		dataType: double
		lineageTag: fafb9e3c-31c6-44ea-83c1-69a1d4a2e5f3
		summarizeBy: sum
		sourceColumn: 产品/基准成本

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 公司
		dataType: string
		lineageTag: f00bf6bb-8cab-494a-862c-0b30b180aa4c
		summarizeBy: none
		sourceColumn: 公司

		annotation SummarizationSetBy = Automatic

	column 销售订单行/仓库
		dataType: string
		lineageTag: 8acb42c7-de73-41fc-a57c-eff6703a5fa0
		summarizeBy: none
		sourceColumn: 销售订单行/仓库

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 1fd4a3be-bb48-4787-8354-74f78b032be9
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 产品分类 =
			
			IF(
			    'FactSalesAll'[产品/产品类别/中文名称] = "冰淇淋",
			    "冰淇淋",
			    IF(
			        'FactSalesAll'[产品/产品类别/上级名称] = "美容 & 健康 & 居家",
			        "美妆",
			        "其他"
			    )
			)
		lineageTag: 3c64fd6a-d591-4d67-8625-ac31eed87740
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 订单创建人_显示 =
			
			VAR CreatorName =
			    TRIM (
			        COALESCE (
			            FactSalesAll[销售订单行/创建人],
			            ""
			        )
			    )
			RETURN
			    IF (
			        CreatorName = "",
			        "未知人员",
			        CreatorName
			    )
		lineageTag: 7b6b687b-63ca-4653-baf6-be3a91e883d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 发票/账单日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: aefb2506-e5eb-4e51-bb81-d158021db647
		summarizeBy: none
		sourceColumn: 发票/账单日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 销售订单行/订单参考号
		dataType: string
		lineageTag: fe62c2fe-0f17-46e8-baf3-29f9259dd14f
		summarizeBy: none
		sourceColumn: 销售订单行/订单参考号

		annotation SummarizationSetBy = Automatic

	column 销售订单行/客户
		dataType: string
		lineageTag: a74f39e5-408c-43ac-9315-6462346dca89
		summarizeBy: none
		sourceColumn: 销售订单行/客户

		annotation SummarizationSetBy = Automatic

	column 折扣后单价
		dataType: double
		lineageTag: 69f5c96a-0079-492c-b4e6-6d29a2fb1615
		summarizeBy: sum
		sourceColumn: 折扣后单价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 会计科目/类型
		dataType: string
		lineageTag: 1769e0ea-ab07-4f0c-b5a3-593239465771
		summarizeBy: none
		sourceColumn: 会计科目/类型

		annotation SummarizationSetBy = Automatic

	column 客户渠道 =
			
			VAR SalespersonName =
			    UPPER(
			        TRIM(
			            COALESCE(
			                FactSalesAll[销售订单行/创建人],
			                ""
			            )
			        )
			    )
			VAR CustomerName =
			    UPPER(
			        TRIM(
			            COALESCE(
			                FactSalesAll[合作伙伴],
			                ""
			            )
			        )
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        SalespersonName = "MAINSTREAM", "主流",
			        CustomerName IN {
			            "Harbor Spice Co",
			            "Summit Seasoning, LLC"
			        }, "代理",
			        "亚裔"
			    )
		lineageTag: 9f934f39-82d2-4b8e-8eab-64b657cd6269
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 数量_1
		dataType: double
		lineageTag: 6a40eb99-f9a3-40dc-a92d-e4e0bfe1f4f4
		summarizeBy: sum
		sourceColumn: 数量_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactSalesAll = m
		mode: import
		source =
				let
				    Source = Csv.Document((if Text.StartsWith(DataRoot, "http") then Web.Contents(DataRoot & "/sales_invoice_lines.csv") else File.Contents(DataRoot & "\sales_invoice_lines.csv")),[Delimiter=",", Columns=28, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"数量", type text}, {"发票/账单日期", type date}, {"产品/内部参考号", type text}, {"产品/名称", type text}, {"产品/CN 品牌", type text}, {"产品/产品类别/中文名称", type text}, {"产品/产品类别/上级名称", type text}, {"产品/计量单位", type text}, {"合作伙伴", type text}, {"合作伙伴/参考", type text}, {"合作伙伴/销售员", type text}, {"合作伙伴/客户类型", type text}, {"合作伙伴/完整地址", type text}, {"合作伙伴/城市", type text}, {"合作伙伴/省/州", type text}, {"销售订单行/销售人员", type text}, {"销售订单行/创建人", type text}, {"数量_1", type number}, {"单价", type number}, {"小计", type number}, {"产品/基准成本", type number}, {"公司", type text}, {"销售订单行/仓库", type text}, {"Type", type text}, {"折扣后单价", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([#"会计科目/类型"] = "收入")),
				    #"Clean Personnel" = Table.TransformColumns(
				        #"Filtered Rows",
				        {
				            {
				                "销售订单行/销售人员",
				                each
				                    let
				                        Name =
				                            if _ = null
				                            then ""
				                            else Text.Trim(Text.From(_))
				                    in
				                        if Name = ""
				                        then "未知人员"
				                        else Name,
				                type text
				            },
				            {
				                "销售订单行/创建人",
				                each
				                    let
				                        Name =
				                            if _ = null
				                            then ""
				                            else Text.Trim(Text.From(_))
				                    in
				                        if Name = ""
				                        then "未知人员"
				                        else Name,
				                type text
				            }
				        }
				    ),
				    #"删除期初数据SKU" =
				    Table.SelectRows(
				        #"Filtered Rows",
				        each
				            Text.Upper(
				                Text.Trim(
				                    Text.From(
				                        [#"产品/内部参考号"]
				                    )
				                )
				            ) <> "INITIALIZE"
				            and Text.Trim(
				                Text.From(
				                    [#"产品/名称"]
				                )
				            ) <> "期初数据SKU"
				    ),
				    #"Renamed Columns" = Table.RenameColumns(删除期初数据SKU,{{"数量", "发票编号"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

