table FactPurchaseOrder
	lineageTag: 39e1441f-73c2-44b1-b932-4261d38a470f

	column 订单行/订单关联
		dataType: string
		lineageTag: 1c04dced-3c3d-42ff-b9a4-567fa9aeff06
		summarizeBy: none
		sourceColumn: 订单行/订单关联

		annotation SummarizationSetBy = Automatic

	column 订单行/产品
		dataType: string
		lineageTag: c94238d5-b726-49e1-abd3-5eacc73b69cb
		summarizeBy: none
		sourceColumn: 订单行/产品

		annotation SummarizationSetBy = Automatic

	column 订单行/单价
		dataType: double
		lineageTag: 86610a6e-1853-49ff-8b63-82d5784eb09d
		summarizeBy: sum
		sourceColumn: 订单行/单价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 订单行/数量
		dataType: int64
		formatString: 0
		lineageTag: a47d0e3f-bdeb-4a57-bc91-c33cc0f30bc4
		summarizeBy: sum
		sourceColumn: 订单行/数量

		annotation SummarizationSetBy = Automatic

	column 订单行/已接收数量
		dataType: int64
		formatString: 0
		lineageTag: ebf37e26-88ed-494f-9fd0-dd5f0bd9c7b8
		summarizeBy: sum
		sourceColumn: 订单行/已接收数量

		annotation SummarizationSetBy = Automatic

	column 订单行/小计
		dataType: double
		lineageTag: 95fd53da-ef69-4365-be40-be9dccda53a6
		summarizeBy: sum
		sourceColumn: 订单行/小计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 订单行/确认日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b24c79d-5405-4113-8228-b2a6cc089a3c
		summarizeBy: none
		sourceColumn: 订单行/确认日期

		variation Variation
			isDefault
			relationship: 22d00cc3-b58d-4a1b-90c7-f4ae3a4dff73
			defaultHierarchy: LocalDateTable_f7066da2-9c07-4515-b867-b9e457b5c538.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 订单行/预计到货时间
		dataType: dateTime
		formatString: General Date
		lineageTag: bd6efa2c-9509-4f6c-9259-0db137ca2456
		summarizeBy: none
		sourceColumn: 订单行/预计到货时间

		variation Variation
			isDefault
			relationship: 4cf92213-27d5-48bb-bb5e-d475c2ede5bd
			defaultHierarchy: LocalDateTable_f1e76bae-a9ad-4d6f-9264-eeb2c1929e05.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 订单行/合作伙伴
		dataType: string
		lineageTag: e90cd6c6-864e-4b99-a376-a06807a57d5a
		summarizeBy: none
		sourceColumn: 订单行/合作伙伴

		annotation SummarizationSetBy = Automatic

	column 订单行/公司
		dataType: string
		lineageTag: 97f028df-dd3d-44e1-a031-34af80af7830
		summarizeBy: none
		sourceColumn: 订单行/公司

		annotation SummarizationSetBy = Automatic

	column 订单行/创建人
		dataType: string
		lineageTag: 1ab81375-dfa9-47b8-a429-060942d74e2d
		summarizeBy: none
		sourceColumn: 订单行/创建人

		annotation SummarizationSetBy = Automatic

	column 订单行/状态
		dataType: string
		lineageTag: ee56b0b6-8b98-42eb-998b-a12910cc601e
		summarizeBy: none
		sourceColumn: 订单行/状态

		annotation SummarizationSetBy = Automatic

	column 订单行/订单关联/实际发货日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1f28f7a-9c6f-4796-9c1e-b911c043e19b
		summarizeBy: none
		sourceColumn: 订单行/订单关联/实际发货日期

		variation Variation
			isDefault
			relationship: a279a163-2daf-4f4e-9ea0-9e20ce826a88
			defaultHierarchy: LocalDateTable_386c7b45-d32c-4bf3-9fa3-d11c0d8264c0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 采购订单号_标准
		dataType: string
		lineageTag: cb806833-cf76-4183-8577-9e2d999f4ecf
		summarizeBy: none
		sourceColumn: 采购订单号_标准

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: e14e7e67-7d96-4c99-bc89-e905cca04d28
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column 采购订单SKU键
		dataType: string
		lineageTag: 9f736d6b-f62a-4f56-b9a8-d474668b5043
		summarizeBy: none
		sourceColumn: 采购订单SKU键

		annotation SummarizationSetBy = Automatic

	column 采购记录类型
		dataType: string
		lineageTag: 2bdb82e5-9a0a-4099-b8c6-c69c1fe5d6c7
		summarizeBy: none
		sourceColumn: 采购记录类型

		annotation SummarizationSetBy = Automatic

	column 采购订单ID
		dataType: int64
		formatString: 0
		lineageTag: 5c99b327-1195-48b3-9085-6964dd086af9
		summarizeBy: count
		sourceColumn: 采购订单ID

		annotation SummarizationSetBy = Automatic

	column 实际发货日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9e44d2c0-a822-46bc-ae76-f22b1498147f
		summarizeBy: none
		sourceColumn: 实际发货日期

		variation Variation
			isDefault
			relationship: 0bb4f8c9-690a-4b02-b293-c20449543e29
			defaultHierarchy: LocalDateTable_a4b66483-c236-4cc3-8084-5e5cda2f0387.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 实际到达日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 82ce6ac3-36df-488e-ba09-70429861c2cd
		summarizeBy: none
		sourceColumn: 实际到达日期

		variation Variation
			isDefault
			relationship: 42ef53b9-2b06-4f4a-8a28-dab3045a36ff
			defaultHierarchy: LocalDateTable_8375bf58-4851-4d14-b0b6-8c2dc4bb969d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 到达状态
		dataType: string
		lineageTag: 9805f1af-79b6-427f-80db-ed17958077c6
		summarizeBy: none
		sourceColumn: 到达状态

		annotation SummarizationSetBy = Automatic

	column 最终实际发货日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d09d181-821a-474e-b5d0-fc75e148366a
		summarizeBy: none
		sourceColumn: 最终实际发货日期

		variation Variation
			isDefault
			relationship: 71725ef9-0e46-455d-a57c-e2b86232baaa
			defaultHierarchy: LocalDateTable_045e5c35-79d3-4290-901e-f3a740b02b19.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 未接收数量
		dataType: double
		lineageTag: 1f9907b8-3ac4-4904-b18c-fe0740507688
		summarizeBy: sum
		sourceColumn: 未接收数量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计提前期天数
		dataType: double
		lineageTag: b9d71443-3714-4f1b-9fb3-91899edd6002
		summarizeBy: sum
		sourceColumn: 预计提前期天数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 实际总提前期天数
		dataType: double
		lineageTag: c145b1ac-c201-4e43-884f-48898a769cda
		summarizeBy: sum
		sourceColumn: 实际总提前期天数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 实际运输天数
		dataType: double
		lineageTag: 5de24ed5-0e7a-4ecd-9b84-094b41632be5
		summarizeBy: sum
		sourceColumn: 实际运输天数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 到货延误天数
		dataType: double
		lineageTag: d28fbe35-2a49-4f05-8970-e3dca3d36333
		summarizeBy: sum
		sourceColumn: 到货延误天数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 是否逾期未到
		dataType: int64
		formatString: 0
		lineageTag: 635d6a57-d2df-4079-adbf-1c5b51edb68c
		summarizeBy: sum
		sourceColumn: 是否逾期未到

		annotation SummarizationSetBy = Automatic

	column 采购状态分类
		dataType: string
		lineageTag: b6821ade-3788-4d50-a785-17385cfe64ae
		summarizeBy: none
		sourceColumn: 采购状态分类

		annotation SummarizationSetBy = Automatic

	column 提前期记录有效
		dataType: string
		lineageTag: 7b0fdd1f-7679-4df5-996a-607865550ded
		summarizeBy: none
		sourceColumn: 提前期记录有效

		annotation SummarizationSetBy = Automatic

	partition FactPurchaseOrder = m
		mode: import
		source =
				let
				    #"Changed Type" = PurchaseOrderLines,
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "采购订单号_标准", each let
				    OrderText = Text.Trim([#"订单行/订单关联"])
				in
				    Text.Trim(
				        if Text.Contains(OrderText, "(")
				        then Text.BeforeDelimiter(OrderText, "(")
				        else OrderText
				    )),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "SKU", each try
				    Text.Trim(
				        Text.BetweenDelimiters(
				            [#"订单行/产品"],
				            "[",
				            "]"
				        )
				    )
				otherwise
				    null),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "采购订单SKU键", each [采购订单号_标准] & "|" & [SKU]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "采购记录类型", each if [#"订单行/数量"] > 0 then "正常采购"
				else if [#"订单行/数量"] < 0 then "退货或冲销"
				else "零数量"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom3", {"采购订单号_标准"}, PurchaseSupplement, {"采购订单号_标准"}, "PurchaseSupplement", JoinKind.LeftOuter),
				    #"Expanded PurchaseSupplement" = Table.ExpandTableColumn(#"Merged Queries", "PurchaseSupplement", {"采购订单ID", "实际发货日期", "实际到达日期", "到达状态"}, {"PurchaseSupplement.采购订单ID", "PurchaseSupplement.实际发货日期", "PurchaseSupplement.实际到达日期", "PurchaseSupplement.到达状态"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PurchaseSupplement",{{"PurchaseSupplement.采购订单ID", "采购订单ID"}, {"PurchaseSupplement.实际发货日期", "实际发货日期"}, {"PurchaseSupplement.实际到达日期", "实际到达日期"}, {"PurchaseSupplement.到达状态", "到达状态"}}),
				    #"Added Custom4" = Table.AddColumn(#"Renamed Columns", "最终实际发货日期", each if [实际发货日期] <> null then
				    [实际发货日期]
				else
				    [#"订单行/订单关联/实际发货日期"]),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "未接收数量", each let
				    PurchaseQty =
				        if [#"订单行/数量"] = null
				        then 0
				        else [#"订单行/数量"],
				
				    ReceivedQty =
				        if [#"订单行/已接收数量"] = null
				        then 0
				        else [#"订单行/已接收数量"],
				
				    RemainingQty =
				        PurchaseQty - ReceivedQty
				in
				    if PurchaseQty <= 0 then
				        0
				    else if RemainingQty > 0 then
				        RemainingQty
				    else
				        0),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "预计提前期天数", each let
				    ConfirmDate = [#"订单行/确认日期"],
				    ExpectedDate = [#"订单行/预计到货时间"]
				in
				    if ConfirmDate = null or ExpectedDate = null then
				        null
				    else if ExpectedDate < ConfirmDate then
				        null
				    else
				        Duration.TotalDays(ExpectedDate - ConfirmDate)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom6",{{"预计提前期天数", type number}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type1", "实际总提前期天数", each let
				    StartDate = [#"订单行/确认日期"],
				    ArrivalDate = [实际到达日期]
				in
				    if StartDate = null or ArrivalDate = null then
				        null
				    else if ArrivalDate < StartDate then
				        null
				    else
				        Duration.TotalDays(ArrivalDate - StartDate)),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom7",{{"实际总提前期天数", type number}}),
				    #"Added Custom8" = Table.AddColumn(#"Changed Type2", "实际运输天数", each let
				    ShipDate =
				        try DateTime.From([最终实际发货日期])
				        otherwise null,
				
				    ArrivalDate =
				        try DateTime.From([实际到达日期])
				        otherwise null
				in
				    if ShipDate = null or ArrivalDate = null then
				        null
				    else if ArrivalDate < ShipDate then
				        null
				    else
				        Duration.TotalDays(
				            ArrivalDate - ShipDate
				        )),
				    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "到货延误天数", each let
				    ExpectedDate = [#"订单行/预计到货时间"],
				    ArrivalDate = [实际到达日期]
				in
				    if ExpectedDate = null or ArrivalDate = null then
				        null
				    else
				        Duration.TotalDays(ArrivalDate - ExpectedDate)),
				    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "是否逾期未到", each let
				    ExpectedDate = [#"订单行/预计到货时间"],
				    ArrivalDate = [实际到达日期],
				    RemainingQty = [未接收数量]
				in
				    if ExpectedDate = null then
				        0
				    else if ArrivalDate = null
				        and RemainingQty > 0
				        and ExpectedDate < DateTime.LocalNow()
				    then
				        1
				    else
				        0),
				    #"Added Custom11" = Table.AddColumn(#"Added Custom10", "采购状态分类", each let
				    PurchaseQty =
				        if [#"订单行/数量"] = null
				        then 0
				        else [#"订单行/数量"],
				
				    ReceivedQty =
				        if [#"订单行/已接收数量"] = null
				        then 0
				        else [#"订单行/已接收数量"],
				
				    ArrivalDate = [实际到达日期]
				in
				    if PurchaseQty < 0 then
				        "退货或冲销"
				    else if PurchaseQty = 0 then
				        "零数量"
				    else if ReceivedQty >= PurchaseQty then
				        "全部接收"
				    else if ReceivedQty > 0 then
				        "部分接收"
				    else if ArrivalDate <> null then
				        "已到达未登记接收"
				    else
				        "未接收"),
				    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "提前期记录有效", each let
				    PurchaseQty =
				        if [#"订单行/数量"] = null
				        then 0
				        else [#"订单行/数量"],
				
				    OrderStatus =
				        if [#"订单行/状态"] = null
				        then ""
				        else Text.Lower(Text.Trim([#"订单行/状态"])),
				
				    SKUValue =
				        if [SKU] = null
				        then ""
				        else Text.Trim([SKU]),
				
				    OrderNumber =
				        if [采购订单号_标准] = null
				        then ""
				        else Text.Trim([采购订单号_标准]),
				
				    LeadDays = [实际总提前期天数]
				in
				    if PurchaseQty <= 0 then 0
				    else if SKUValue = "" then 0
				    else if OrderNumber = "" then 0
				    else if OrderStatus <> "done" then 0
				    else if [采购创建日期] = null then 0
				    else if [实际到达日期] = null then 0
				    else if LeadDays = null then 0
				    else if LeadDays < 0 then 0
				    else if LeadDays > 365 then 0
				    else 1),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom12",{"提前期记录有效"}),
				    #"Added Custom13" = Table.AddColumn(#"Removed Columns", "提前期记录有效", each let
				    PurchaseQty =
				        if [#"订单行/数量"] = null
				        then 0
				        else [#"订单行/数量"],
				
				    OrderStatus =
				        if [#"订单行/状态"] = null
				        then ""
				        else Text.Lower(Text.Trim([#"订单行/状态"])),
				
				    SKUValue =
				        if [SKU] = null
				        then ""
				        else Text.Trim([SKU]),
				
				    OrderNumber =
				        if [采购订单号_标准] = null
				        then ""
				        else Text.Trim([采购订单号_标准]),
				
				    LeadDays = [实际总提前期天数]
				in
				    if PurchaseQty <= 0 then 0
				    else if SKUValue = "" then 0
				    else if OrderNumber = "" then 0
				    else if OrderStatus <> "done" then 0
				    else if [#"订单行/确认日期"] = null then 0
				    else if [实际到达日期] = null then 0
				    else if LeadDays = null then 0
				    else if LeadDays < 0 then 0
				    else if LeadDays > 365 then 0
				    else 1),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom13",{{"未接收数量", type number}, {"最终实际发货日期", type date}, {"实际运输天数", type number}, {"实际总提前期天数", type number}, {"预计提前期天数", type number}, {"到货延误天数", type number}, {"是否逾期未到", Int64.Type}, {"采购状态分类", type text}, {"采购记录类型", type text}, {"采购订单SKU键", type text}, {"SKU", type text}, {"采购订单号_标准", type text}, {"订单行/状态", type text}, {"订单行/创建人", type text}, {"订单行/公司", type text}, {"订单行/合作伙伴", type text}, {"订单行/数量", Int64.Type}, {"订单行/已接收数量", Int64.Type}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

