table FactPurchaseOrder
	lineageTag: 39e1441f-73c2-44b1-b932-4261d38a470f

	column 'Order Line/Order Reference'
		dataType: string
		lineageTag: 1c04dced-3c3d-42ff-b9a4-567fa9aeff06
		summarizeBy: none
		sourceColumn: Order Line/Order Reference

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Product'
		dataType: string
		lineageTag: c94238d5-b726-49e1-abd3-5eacc73b69cb
		summarizeBy: none
		sourceColumn: Order Line/Product

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Unit Price'
		dataType: double
		lineageTag: 86610a6e-1853-49ff-8b63-82d5784eb09d
		summarizeBy: sum
		sourceColumn: Order Line/Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Line/Quantity'
		dataType: int64
		formatString: 0
		lineageTag: a47d0e3f-bdeb-4a57-bc91-c33cc0f30bc4
		summarizeBy: sum
		sourceColumn: Order Line/Quantity

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Received Qty'
		dataType: int64
		formatString: 0
		lineageTag: ebf37e26-88ed-494f-9fd0-dd5f0bd9c7b8
		summarizeBy: sum
		sourceColumn: Order Line/Received Qty

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Subtotal'
		dataType: double
		lineageTag: 95fd53da-ef69-4365-be40-be9dccda53a6
		summarizeBy: sum
		sourceColumn: Order Line/Subtotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Line/Confirmed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b24c79d-5405-4113-8228-b2a6cc089a3c
		summarizeBy: none
		sourceColumn: Order Line/Confirmed Date

		variation Variation
			isDefault
			relationship: 22d00cc3-b58d-4a1b-90c7-f4ae3a4dff73
			defaultHierarchy: LocalDateTable_f7066da2-9c07-4515-b867-b9e457b5c538.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Expected Arrival Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: bd6efa2c-9509-4f6c-9259-0db137ca2456
		summarizeBy: none
		sourceColumn: Order Line/Expected Arrival Time

		variation Variation
			isDefault
			relationship: 4cf92213-27d5-48bb-bb5e-d475c2ede5bd
			defaultHierarchy: LocalDateTable_f1e76bae-a9ad-4d6f-9264-eeb2c1929e05.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Partner'
		dataType: string
		lineageTag: e90cd6c6-864e-4b99-a376-a06807a57d5a
		summarizeBy: none
		sourceColumn: Order Line/Partner

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Company'
		dataType: string
		lineageTag: 97f028df-dd3d-44e1-a031-34af80af7830
		summarizeBy: none
		sourceColumn: Order Line/Company

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Created By'
		dataType: string
		lineageTag: 1ab81375-dfa9-47b8-a429-060942d74e2d
		summarizeBy: none
		sourceColumn: Order Line/Created By

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Status'
		dataType: string
		lineageTag: ee56b0b6-8b98-42eb-998b-a12910cc601e
		summarizeBy: none
		sourceColumn: Order Line/Status

		annotation SummarizationSetBy = Automatic

	column 'Order Line/Order Reference/Actual Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1f28f7a-9c6f-4796-9c1e-b911c043e19b
		summarizeBy: none
		sourceColumn: Order Line/Order Reference/Actual Ship Date

		variation Variation
			isDefault
			relationship: a279a163-2daf-4f4e-9ea0-9e20ce826a88
			defaultHierarchy: LocalDateTable_386c7b45-d32c-4bf3-9fa3-d11c0d8264c0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Purchase Order No_Std'
		dataType: string
		lineageTag: cb806833-cf76-4183-8577-9e2d999f4ecf
		summarizeBy: none
		sourceColumn: Purchase Order No_Std

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: e14e7e67-7d96-4c99-bc89-e905cca04d28
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order SKU Key'
		dataType: string
		lineageTag: 9f736d6b-f62a-4f56-b9a8-d474668b5043
		summarizeBy: none
		sourceColumn: Purchase Order SKU Key

		annotation SummarizationSetBy = Automatic

	column 'Purchase Record Type'
		dataType: string
		lineageTag: 2bdb82e5-9a0a-4099-b8c6-c69c1fe5d6c7
		summarizeBy: none
		sourceColumn: Purchase Record Type

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 5c99b327-1195-48b3-9085-6964dd086af9
		summarizeBy: count
		sourceColumn: Purchase Order ID

		annotation SummarizationSetBy = Automatic

	column 'Actual Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9e44d2c0-a822-46bc-ae76-f22b1498147f
		summarizeBy: none
		sourceColumn: Actual Ship Date

		variation Variation
			isDefault
			relationship: 0bb4f8c9-690a-4b02-b293-c20449543e29
			defaultHierarchy: LocalDateTable_a4b66483-c236-4cc3-8084-5e5cda2f0387.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Actual Arrival Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 82ce6ac3-36df-488e-ba09-70429861c2cd
		summarizeBy: none
		sourceColumn: Actual Arrival Date

		variation Variation
			isDefault
			relationship: 42ef53b9-2b06-4f4a-8a28-dab3045a36ff
			defaultHierarchy: LocalDateTable_8375bf58-4851-4d14-b0b6-8c2dc4bb969d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Arrival Status'
		dataType: string
		lineageTag: 9805f1af-79b6-427f-80db-ed17958077c6
		summarizeBy: none
		sourceColumn: Arrival Status

		annotation SummarizationSetBy = Automatic

	column 'Final Actual Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d09d181-821a-474e-b5d0-fc75e148366a
		summarizeBy: none
		sourceColumn: Final Actual Ship Date

		variation Variation
			isDefault
			relationship: 71725ef9-0e46-455d-a57c-e2b86232baaa
			defaultHierarchy: LocalDateTable_045e5c35-79d3-4290-901e-f3a740b02b19.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Unreceived Qty'
		dataType: double
		lineageTag: 1f9907b8-3ac4-4904-b18c-fe0740507688
		summarizeBy: sum
		sourceColumn: Unreceived Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Expected Lead Time Days'
		dataType: double
		lineageTag: b9d71443-3714-4f1b-9fb3-91899edd6002
		summarizeBy: sum
		sourceColumn: Expected Lead Time Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Total Lead Time Days'
		dataType: double
		lineageTag: c145b1ac-c201-4e43-884f-48898a769cda
		summarizeBy: sum
		sourceColumn: Actual Total Lead Time Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Transit Days'
		dataType: double
		lineageTag: 5de24ed5-0e7a-4ecd-9b84-094b41632be5
		summarizeBy: sum
		sourceColumn: Actual Transit Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Arrival Delay Days'
		dataType: double
		lineageTag: d28fbe35-2a49-4f05-8970-e3dca3d36333
		summarizeBy: sum
		sourceColumn: Arrival Delay Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Overdue'
		dataType: int64
		formatString: 0
		lineageTag: 635d6a57-d2df-4079-adbf-1c5b51edb68c
		summarizeBy: sum
		sourceColumn: Is Overdue

		annotation SummarizationSetBy = Automatic

	column 'Purchase Status Class'
		dataType: string
		lineageTag: b6821ade-3788-4d50-a785-17385cfe64ae
		summarizeBy: none
		sourceColumn: Purchase Status Class

		annotation SummarizationSetBy = Automatic

	column 'Lead Time Record Valid'
		dataType: string
		lineageTag: 7b0fdd1f-7679-4df5-996a-607865550ded
		summarizeBy: none
		sourceColumn: Lead Time Record Valid

		annotation SummarizationSetBy = Automatic

	partition FactPurchaseOrder = m
		mode: import
		source =
				let
				    #"Changed Type" = PurchaseOrderLines,
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Purchase Order No_Std", each let
				    OrderText = Text.Trim([#"Order Line/Order Reference"])
				in
				    Text.Trim(
				        if Text.Contains(OrderText, "(")
				        then Text.BeforeDelimiter(OrderText, "(")
				        else OrderText
				    )),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "SKU", each try
				    Text.Trim(
				        Text.BetweenDelimiters(
				            [#"Order Line/Product"],
				            "[",
				            "]"
				        )
				    )
				otherwise
				    null),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Purchase Order SKU Key", each [Purchase Order No_Std] & "|" & [SKU]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Purchase Record Type", each if [#"Order Line/Quantity"] > 0 then "Normal Purchase"
				else if [#"Order Line/Quantity"] < 0 then "Return or Reversal"
				else "Zero Quantity"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom3", {"Purchase Order No_Std"}, PurchaseSupplement, {"Purchase Order No_Std"}, "PurchaseSupplement", JoinKind.LeftOuter),
				    #"Expanded PurchaseSupplement" = Table.ExpandTableColumn(#"Merged Queries", "PurchaseSupplement", {"Purchase Order ID", "Actual Ship Date", "Actual Arrival Date", "Arrival Status"}, {"PurchaseSupplement.Purchase Order ID", "PurchaseSupplement.Actual Ship Date", "PurchaseSupplement.Actual Arrival Date", "PurchaseSupplement.Arrival Status"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PurchaseSupplement",{{"PurchaseSupplement.Purchase Order ID", "Purchase Order ID"}, {"PurchaseSupplement.Actual Ship Date", "Actual Ship Date"}, {"PurchaseSupplement.Actual Arrival Date", "Actual Arrival Date"}, {"PurchaseSupplement.Arrival Status", "Arrival Status"}}),
				    #"Added Custom4" = Table.AddColumn(#"Renamed Columns", "Final Actual Ship Date", each if [Actual Ship Date] <> null then
				    [Actual Ship Date]
				else
				    [#"Order Line/Order Reference/Actual Ship Date"]),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Unreceived Qty", each let
				    PurchaseQty =
				        if [#"Order Line/Quantity"] = null
				        then 0
				        else [#"Order Line/Quantity"],
				
				    ReceivedQty =
				        if [#"Order Line/Received Qty"] = null
				        then 0
				        else [#"Order Line/Received Qty"],
				
				    RemainingQty =
				        PurchaseQty - ReceivedQty
				in
				    if PurchaseQty <= 0 then
				        0
				    else if RemainingQty > 0 then
				        RemainingQty
				    else
				        0),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Expected Lead Time Days", each let
				    ConfirmDate = [#"Order Line/Confirmed Date"],
				    ExpectedDate = [#"Order Line/Expected Arrival Time"]
				in
				    if ConfirmDate = null or ExpectedDate = null then
				        null
				    else if ExpectedDate < ConfirmDate then
				        null
				    else
				        Duration.TotalDays(ExpectedDate - ConfirmDate)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom6",{{"Expected Lead Time Days", type number}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type1", "Actual Total Lead Time Days", each let
				    StartDate = [#"Order Line/Confirmed Date"],
				    ArrivalDate = [Actual Arrival Date]
				in
				    if StartDate = null or ArrivalDate = null then
				        null
				    else if ArrivalDate < StartDate then
				        null
				    else
				        Duration.TotalDays(ArrivalDate - StartDate)),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom7",{{"Actual Total Lead Time Days", type number}}),
				    #"Added Custom8" = Table.AddColumn(#"Changed Type2", "Actual Transit Days", each let
				    ShipDate =
				        try DateTime.From([Final Actual Ship Date])
				        otherwise null,
				
				    ArrivalDate =
				        try DateTime.From([Actual Arrival Date])
				        otherwise null
				in
				    if ShipDate = null or ArrivalDate = null then
				        null
				    else if ArrivalDate < ShipDate then
				        null
				    else
				        Duration.TotalDays(
				            ArrivalDate - ShipDate
				        )),
				    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "Arrival Delay Days", each let
				    ExpectedDate = [#"Order Line/Expected Arrival Time"],
				    ArrivalDate = [Actual Arrival Date]
				in
				    if ExpectedDate = null or ArrivalDate = null then
				        null
				    else
				        Duration.TotalDays(ArrivalDate - ExpectedDate)),
				    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "Is Overdue", each let
				    ExpectedDate = [#"Order Line/Expected Arrival Time"],
				    ArrivalDate = [Actual Arrival Date],
				    RemainingQty = [Unreceived Qty]
				in
				    if ExpectedDate = null then
				        0
				    else if ArrivalDate = null
				        and RemainingQty > 0
				        and ExpectedDate < DateTime.LocalNow()
				    then
				        1
				    else
				        0),
				    #"Added Custom11" = Table.AddColumn(#"Added Custom10", "Purchase Status Class", each let
				    PurchaseQty =
				        if [#"Order Line/Quantity"] = null
				        then 0
				        else [#"Order Line/Quantity"],
				
				    ReceivedQty =
				        if [#"Order Line/Received Qty"] = null
				        then 0
				        else [#"Order Line/Received Qty"],
				
				    ArrivalDate = [Actual Arrival Date]
				in
				    if PurchaseQty < 0 then
				        "Return or Reversal"
				    else if PurchaseQty = 0 then
				        "Zero Quantity"
				    else if ReceivedQty >= PurchaseQty then
				        "Fully Received"
				    else if ReceivedQty > 0 then
				        "Partially Received"
				    else if ArrivalDate <> null then
				        "Arrived Not Received"
				    else
				        "Not Received"),
				    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Lead Time Record Valid", each let
				    PurchaseQty =
				        if [#"Order Line/Quantity"] = null
				        then 0
				        else [#"Order Line/Quantity"],
				
				    OrderStatus =
				        if [#"Order Line/Status"] = null
				        then ""
				        else Text.Lower(Text.Trim([#"Order Line/Status"])),
				
				    SKUValue =
				        if [SKU] = null
				        then ""
				        else Text.Trim([SKU]),
				
				    OrderNumber =
				        if [Purchase Order No_Std] = null
				        then ""
				        else Text.Trim([Purchase Order No_Std]),
				
				    LeadDays = [Actual Total Lead Time Days]
				in
				    if PurchaseQty <= 0 then 0
				    else if SKUValue = "" then 0
				    else if OrderNumber = "" then 0
				    else if OrderStatus <> "done" then 0
				    else if [Purchase Created Date] = null then 0
				    else if [Actual Arrival Date] = null then 0
				    else if LeadDays = null then 0
				    else if LeadDays < 0 then 0
				    else if LeadDays > 365 then 0
				    else 1),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom12",{"Lead Time Record Valid"}),
				    #"Added Custom13" = Table.AddColumn(#"Removed Columns", "Lead Time Record Valid", each let
				    PurchaseQty =
				        if [#"Order Line/Quantity"] = null
				        then 0
				        else [#"Order Line/Quantity"],
				
				    OrderStatus =
				        if [#"Order Line/Status"] = null
				        then ""
				        else Text.Lower(Text.Trim([#"Order Line/Status"])),
				
				    SKUValue =
				        if [SKU] = null
				        then ""
				        else Text.Trim([SKU]),
				
				    OrderNumber =
				        if [Purchase Order No_Std] = null
				        then ""
				        else Text.Trim([Purchase Order No_Std]),
				
				    LeadDays = [Actual Total Lead Time Days]
				in
				    if PurchaseQty <= 0 then 0
				    else if SKUValue = "" then 0
				    else if OrderNumber = "" then 0
				    else if OrderStatus <> "done" then 0
				    else if [#"Order Line/Confirmed Date"] = null then 0
				    else if [Actual Arrival Date] = null then 0
				    else if LeadDays = null then 0
				    else if LeadDays < 0 then 0
				    else if LeadDays > 365 then 0
				    else 1),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom13",{{"Unreceived Qty", type number}, {"Final Actual Ship Date", type date}, {"Actual Transit Days", type number}, {"Actual Total Lead Time Days", type number}, {"Expected Lead Time Days", type number}, {"Arrival Delay Days", type number}, {"Is Overdue", Int64.Type}, {"Purchase Status Class", type text}, {"Purchase Record Type", type text}, {"Purchase Order SKU Key", type text}, {"SKU", type text}, {"Purchase Order No_Std", type text}, {"Order Line/Status", type text}, {"Order Line/Created By", type text}, {"Order Line/Company", type text}, {"Order Line/Partner", type text}, {"Order Line/Quantity", Int64.Type}, {"Order Line/Received Qty", Int64.Type}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

