table PurchaseSupplement
	lineageTag: 0ea54abe-3ec0-4b88-8fca-16f6c548c413

	column 'Purchase Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 75fa5331-831b-466b-a0c4-54f7ddca18b8
		summarizeBy: count
		sourceColumn: Purchase Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Reference'
		dataType: string
		lineageTag: 71b57956-7a8e-43bd-b500-a88df1e7136d
		summarizeBy: none
		sourceColumn: Order Reference

		annotation SummarizationSetBy = Automatic

	column 'Purchase Created Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 32ba5bd6-1a8e-428f-b844-68bde6b7c426
		summarizeBy: none
		sourceColumn: Purchase Created Date

		variation Variation
			isDefault
			relationship: 94a49b70-07d1-40eb-a2db-e32d66319703
			defaultHierarchy: LocalDateTable_a7ee464b-b7ac-4b49-a112-d36d906344f4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Actual Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b423996a-90fe-4b73-a78a-decf8798d4ef
		summarizeBy: none
		sourceColumn: Actual Ship Date

		variation Variation
			isDefault
			relationship: 084c7935-57b5-4962-a391-8c6927025377
			defaultHierarchy: LocalDateTable_9d622cf0-4654-4ef3-b293-18d0ebb8dd0c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Actual Arrival Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e3a041e-3188-4d05-b825-3e35ad1a90bd
		summarizeBy: none
		sourceColumn: Actual Arrival Date

		variation Variation
			isDefault
			relationship: 50d9dfbc-a091-4ba8-9458-d08ce4ba1743
			defaultHierarchy: LocalDateTable_940fa20f-0f6e-4ac3-bbc1-a6a4b46d9ba1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order No_Std'
		dataType: string
		lineageTag: 2b456126-5690-4188-b1f2-d39ae34bf713
		summarizeBy: none
		sourceColumn: Purchase Order No_Std

		annotation SummarizationSetBy = Automatic

	column 'Arrival Status'
		dataType: string
		lineageTag: fe7228f1-2b52-46e5-b217-ae40559c2fa7
		summarizeBy: none
		sourceColumn: Arrival Status

		annotation SummarizationSetBy = Automatic

	partition PurchaseSupplement = m
		mode: import
		source =
				let
				    Source = Csv.Document((if Text.StartsWith(DataRoot, "http") then Web.Contents(DataRoot & "/purchase_tracking.csv") else File.Contents(DataRoot & "\purchase_tracking.csv")),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Order Reference", type text}, {"Created Date", type datetime}, {"Actual Ship Date", type date}, {"Arrival", type datetime}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Purchase Order No_Std", each let
				    OrderText = Text.Trim([Order Reference])
				in
				    Text.Trim(
				        if Text.Contains(OrderText, "(")
				        then Text.BeforeDelimiter(OrderText, "(")
				        else OrderText
				    )),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Arrival Status", each if [Arrival] <> null then "Arrived"
				else if [Actual Ship Date] <> null then "In Transit"
				else "Not Shipped or Not Maintained"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom1",{{"ID", "Purchase Order ID"}, {"Created Date", "Purchase Created Date"}, {"Arrival", "Actual Arrival Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

